# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
aho-corasick-0.5.3
ansi_term-0.11.0
atty-0.2.14
bitflags-1.2.1
cannoli-0.2.0
clap-2.33.0
hermit-abi-0.1.7
kernel32-sys-0.2.2
lazy_static-1.4.0
libc-0.2.66
memchr-0.1.11
regex-0.1.80
regex-syntax-0.3.9
strsim-0.8.0
textwrap-0.11.0
thread-id-2.0.0
thread_local-0.2.7
unicode-segmentation-0.1.3
unicode-width-0.1.7
unicode_names-0.1.7
utf8-ranges-0.1.3
vec_map-0.8.1
winapi-0.2.8
winapi-0.3.8
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Cannoli Programming Language: written in Rust and also compiles Python to Rust."
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/joncatanio/cannoli"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 MIT Unlicense"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
