# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
advapi32-sys-0.2.0
aho-corasick-0.6.3
atty-0.2.3
backtrace-0.3.3
backtrace-sys-0.1.16
bitflags-0.7.0
bitflags-0.9.1
cargo-0.24.0
cargo-bitbake-0.3.10
cc-1.0.3
cfg-if-0.1.2
cmake-0.1.25
commoncrypto-0.2.0
commoncrypto-sys-0.2.0
conv-0.3.3
core-foundation-0.4.6
core-foundation-sys-0.4.6
crates-io-0.13.0
crossbeam-0.2.10
crossbeam-0.3.2
crypto-hash-0.3.0
curl-0.4.8
curl-sys-0.3.14
custom_derive-0.1.7
dbghelp-sys-0.2.0
docopt-0.8.1
dtoa-0.4.2
either-1.1.0
env_logger-0.4.3
error-chain-0.11.0
filetime-0.1.10
flate2-0.2.19
fnv-1.0.6
foreign-types-0.2.0
fs2-0.4.2
gcc-0.3.53
git2-0.6.6
git2-curl-0.7.0
glob-0.2.11
globset-0.2.1
hex-0.2.0
home-0.3.0
idna-0.1.4
ignore-0.2.2
itertools-0.5.10
itoa-0.3.2
jobserver-0.1.8
kernel32-sys-0.2.2
lazy_static-0.2.8
libc-0.2.29
libgit2-sys-0.6.13
libssh2-sys-0.2.6
libz-sys-1.0.16
log-0.3.8
magenta-0.1.1
magenta-sys-0.1.1
matches-0.1.6
md5-0.3.5
memchr-1.0.1
memchr-2.0.1
miniz-sys-0.1.9
miow-0.2.1
net2-0.2.31
num-traits-0.1.40
num_cpus-1.6.2
openssl-0.9.15
openssl-probe-0.1.1
openssl-sys-0.9.15
percent-encoding-1.0.0
pkg-config-0.3.9
psapi-sys-0.1.0
quote-0.3.15
rand-0.3.16
redox_syscall-0.1.31
redox_termios-0.1.1
regex-0.2.2
regex-syntax-0.4.1
rustc-demangle-0.1.5
same-file-0.1.3
scoped-tls-0.1.0
scopeguard-0.1.2
semver-0.8.0
semver-parser-0.7.0
serde-1.0.16
serde_derive-1.0.16
serde_derive_internals-0.16.0
serde_ignored-0.0.4
serde_json-1.0.5
shell-escape-0.1.3
socket2-0.2.2
strsim-0.6.0
syn-0.11.11
synom-0.11.3
tar-0.4.13
tempdir-0.3.5
termcolor-0.3.3
termion-1.5.1
thread_local-0.3.4
toml-0.4.5
unicode-bidi-0.3.3
unicode-normalization-0.1.5
unicode-xid-0.0.4
unreachable-1.0.0
url-1.5.1
userenv-sys-0.2.0
utf8-ranges-1.0.0
vcpkg-0.2.2
void-1.0.2
walkdir-1.0.7
winapi-0.2.8
winapi-build-0.1.1
wincolor-0.1.4
ws2_32-sys-0.2.1
"

inherit cargo

DESCRIPTION="Generates a BitBake recipe for a package utilizing meta-rust's classes."
HOMEPAGE="https://github.com/cardoe/cargo-bitbake"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT Apache-2.0"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
