# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
aho-corasick-0.6.8
bitflags-1.0.4
calculator-0.1.0
cloudabi-0.0.3
console-0.1.0
cstr-macro-0.1.0
docopt-0.1.0
docopt-1.0.1
duration-0.1.0
fuchsia-zircon-0.3.3
fuchsia-zircon-sys-0.3.3
game_of_life-0.1.0
geometry-0.1.0
helix-0.7.5
itoa-0.4.2
json_builder-0.1.0
lazy_static-1.1.0
libc-0.2.43
libcruby-sys-0.7.5
membership-0.1.0
memchr-2.0.2
proc-macro2-0.4.15
quote-0.6.8
rand-0.5.5
rand_core-0.2.1
redox_syscall-0.1.40
redox_termios-0.1.1
regex-1.0.4
regex-syntax-0.6.2
ryu-0.2.6
serde-1.0.75
serde_derive-1.0.75
serde_json-1.0.26
strsim-0.7.0
syn-0.14.9
termion-1.5.1
text_transform-0.1.0
thread_local-0.3.6
turbo_blank-0.1.0
ucd-util-0.1.1
unicode-xid-0.1.0
unit-0.1.0
utf8-ranges-1.0.1
version_check-0.1.4
winapi-0.3.5
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Embed Rust in your Ruby"
HOMEPAGE="https://usehelix.com"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="ISC" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64 ~x86 ~arm ~arm64"
IUSE=""

DEPEND=""
RDEPEND=""
