# Copyright 2017-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=7

CRATES="
aho-corasick-0.7.3
ansi_term-0.11.0
argon2rs-0.2.5
arrayvec-0.4.10
atty-0.2.11
autocfg-0.1.2
backtrace-0.3.15
backtrace-sys-0.1.28
bitflags-1.0.4
blake2-rfc-0.2.18
byteorder-1.3.1
capstone-0.5.0
capstone-sys-0.9.1
cast-0.2.2
cc-1.0.35
cfg-if-0.1.7
chrono-0.4.6
clap-2.33.0
cloudabi-0.0.3
cmake-0.1.38
constant_time_eq-0.1.3
cranelift-0.30.0
cranelift-bforest-0.30.0
cranelift-codegen-0.30.0
cranelift-codegen-meta-0.30.0
cranelift-entity-0.30.0
cranelift-faerie-0.30.0
cranelift-frontend-0.30.0
cranelift-module-0.30.0
cranelift-native-0.30.0
cranelift-preopt-0.30.0
cranelift-reader-0.30.0
cranelift-simplejit-0.30.0
cranelift-wasm-0.30.0
dirs-1.0.5
env_logger-0.6.1
errno-0.2.4
errno-dragonfly-0.1.1
faerie-0.10.0
failure-0.1.5
failure_derive-0.1.5
file-per-thread-logger-0.1.2
filecheck-0.4.0
fuchsia-cprng-0.1.1
gcc-0.3.55
glob-0.2.11
goblin-0.0.21
hashmap_core-0.1.10
heck-0.3.1
humantime-1.2.0
indexmap-1.0.2
itoa-0.4.3
lazy_static-1.3.0
libc-0.2.51
log-0.4.6
mach-0.2.3
memchr-2.2.0
nodrop-0.1.13
num-integer-0.1.39
num-traits-0.2.6
num_cpus-1.10.0
numtoa-0.1.0
plain-0.2.3
pretty_env_logger-0.3.0
proc-macro2-0.4.27
quick-error-1.2.2
quote-0.6.12
rand_core-0.3.1
rand_core-0.4.0
rand_os-0.1.3
raw-cpuid-6.1.0
rdrand-0.4.0
redox_syscall-0.1.54
redox_termios-0.1.1
redox_users-0.3.0
regex-1.1.6
regex-syntax-0.6.6
region-2.0.0
rustc-demangle-0.1.14
rustc_version-0.2.3
ryu-0.2.7
scoped_threadpool-0.1.9
scroll-0.9.2
scroll_derive-0.9.5
semver-0.9.0
semver-parser-0.7.0
serde-1.0.90
serde_derive-1.0.90
serde_json-1.0.39
string-interner-0.6.3
strsim-0.8.0
structopt-0.2.15
structopt-derive-0.2.15
syn-0.15.32
synstructure-0.10.1
target-lexicon-0.4.0
term-0.5.2
termcolor-1.0.4
termion-1.5.2
textwrap-0.11.0
thread_local-0.3.6
time-0.1.42
ucd-util-0.1.3
unicode-segmentation-1.2.1
unicode-width-0.1.5
unicode-xid-0.1.0
utf8-ranges-1.0.2
vec_map-0.8.1
wabt-0.7.4
wabt-sys-0.5.4
wasmparser-0.29.2
winapi-0.3.7
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.2
winapi-x86_64-pc-windows-gnu-0.4.0
wincolor-1.0.1
"

inherit cargo

DESCRIPTION="Binaries for testing the Cranelift libraries"
HOMEPAGE="https://github.com/CraneStation/cranelift"

SRCHASH=4f69c32572a13f4ded3b05542abf476d1cd2ead8

SRC_URI="https://github.com/CraneStation/cranelift/archive/${SRCHASH}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="Apache-2.0 WITH LLVM-exception" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""

S="${WORKDIR}"/cranelift-${SRCHASH}

src_configure() {
	# Do nothing
	echo "Configuring cranelift..."
}

src_compile() {
	export CARGO_HOME="${ECARGO_HOME}"
	cargo build -j$(makeopts_jobs) --release || die
}

src_install() {
	dobin target/release/clif-util
}
