# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
adler32-0.2.0
ar-0.6.0
bitflags-1.0.3
build_const-0.2.1
byteorder-0.5.3
byteorder-1.2.3
cargo-deb-1.11.0
cargo_toml-0.3.0
cc-1.0.18
cfg-if-0.1.4
crc-1.8.1
dtoa-0.4.3
file-1.1.2
filetime-0.2.1
fuchsia-zircon-0.3.3
fuchsia-zircon-sys-0.3.3
getopts-0.2.18
glob-0.2.11
itoa-0.4.2
libc-0.2.42
lzma-sys-0.1.10
md5-0.3.7
pkg-config-0.3.12
proc-macro2-0.4.8
quick-error-1.2.2
quote-0.6.3
rand-0.4.2
redox_syscall-0.1.40
remove_dir_all-0.5.1
serde-1.0.70
serde_derive-1.0.70
serde_json-1.0.24
syn-0.14.4
tar-0.4.16
tempdir-0.3.7
toml-0.4.6
typed-arena-1.4.1
unicode-width-0.1.5
unicode-xid-0.1.0
winapi-0.3.5
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
xattr-0.2.2
xz2-0.1.5
zopfli-0.3.7
"

inherit cargo

DESCRIPTION="Make Debian packages (.deb) easily with a Cargo subcommand"
HOMEPAGE="https://github.com/mmstick/cargo-deb#readme"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
