# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
aho-corasick-0.6.6
backtrace-0.3.9
backtrace-sys-0.1.24
byteorder-1.2.4
cargo-rpm-0.1.1
cc-1.0.22
cfg-if-0.1.5
failure-0.1.2
failure_derive-0.1.2
filetime-0.2.1
flate2-1.0.2
gumdrop-0.4.0
gumdrop_derive-0.4.1
handlebars-1.0.1
iq-cli-0.1.0
itoa-0.4.2
lazy_static-1.1.0
libc-0.2.43
libz-sys-1.0.20
log-0.4.4
memchr-2.0.1
pest-1.0.6
pest_derive-1.0.8
pkg-config-0.3.13
proc-macro2-0.3.8
proc-macro2-0.4.13
quick-error-1.2.2
quote-0.3.15
quote-0.5.2
quote-0.6.8
redox_syscall-0.1.40
regex-1.0.3
regex-syntax-0.6.2
rustc-demangle-0.1.9
ryu-0.2.5
same-file-1.0.3
serde-1.0.75
serde_derive-1.0.75
serde_json-1.0.26
syn-0.11.11
syn-0.13.11
syn-0.14.9
synom-0.11.3
synstructure-0.9.0
tar-0.4.16
term-0.5.1
thread_local-0.3.6
toml-0.4.6
ucd-util-0.1.1
unicode-xid-0.0.4
unicode-xid-0.1.0
utf8-ranges-1.0.0
vcpkg-0.2.6
version_check-0.1.4
walkdir-2.2.4
winapi-0.3.5
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.1
winapi-x86_64-pc-windows-gnu-0.4.0
xattr-0.2.2
"

inherit cargo

DESCRIPTION="Build RPMs from Rust projects using Cargo"
HOMEPAGE="https://github.com/rustrpm/cargo-rpm/"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
